/**
 * Import this mixin to add color classes to a component or element via props (js literals)
 */
export default {
  props: {
    'color': { type: String, default: '', required: false }, // Selectors
    'bg-color': { type: String, default: '', required: false },
    'black': { type: String, default: 'black', required: false }, // Colors
    'gray': { type: String, default: 'gray', required: false },
    'silver': { type: String, default: 'silver', required: false },
    'white': { type: String, default: 'white', required: false },
    'aqua': { type: String, default: 'aqua', required: false },
    'blue': { type: String, default: 'blue', required: false },
    'navy': { type: String, default: 'navy', required: false },
    'teal': { type: String, default: 'teal', required: false },
    'green': { type: String, default: 'green', required: false },
    'olive': { type: String, default: 'olive', required: false },
    'lime': { type: String, default: 'lime', required: false },
    'yellow': { type: String, default: 'yellow', required: false },
    'orange': { type: String, default: 'orange', required: false },
    'red': { type: String, default: 'red', required: false },
    'fuchsia': { type: String, default: 'fuchsia', required: false },
    'purple': { type: String, default: 'purple', required: false },
    'maroon': { type: String, default: 'maroon', required: false },
    'darken-1': { type: String, default: 'darken-1', required: false },
    'darken-2': { type: String, default: 'darken-2', required: false },
    'darken-3': { type: String, default: 'darken-3', required: false },
    'darken-4': { type: String, default: 'darken-4', required: false },
    'lighten-1': { type: String, default: 'lighten-1', required: false },
    'lighten-2': { type: String, default: 'lighten-2', required: false },
    'lighten-3': { type: String, default: 'lighten-3', required: false },
    'lighten-4': { type: String, default: 'lighten-4', required: false },
    'bg-black': { type: String, default: 'bg-black', required: false }, // Background Colors
    'bg-gray': { type: String, default: 'bg-gray', required: false },
    'bg-silver': { type: String, default: 'bg-silver', required: false },
    'bg-white': { type: String, default: 'bg-white', required: false },
    'bg-aqua': { type: String, default: 'bg-aqua', required: false },
    'bg-blue': { type: String, default: 'bg-blue', required: false },
    'bg-navy': { type: String, default: 'bg-navy', required: false },
    'bg-teal': { type: String, default: 'bg-teal', required: false },
    'bg-green': { type: String, default: 'bg-green', required: false },
    'bg-olive': { type: String, default: 'bg-olive', required: false },
    'bg-lime': { type: String, default: 'bg-lime', required: false },
    'bg-yellow': { type: String, default: 'bg-yellow', required: false },
    'bg-orange': { type: String, default: 'bg-orange', required: false },
    'bg-red': { type: String, default: 'bg-red', required: false },
    'bg-fuchsia': { type: String, default: 'bg-fuchsia', required: false },
    'bg-purple': { type: String, default: 'bg-purple', required: false },
    'bg-maroon': { type: String, default: 'bg-maroon', required: false },
    'bg-darken-1': { type: String, default: 'bg-darken-1', required: false },
    'bg-darken-2': { type: String, default: 'bg-darken-2', required: false },
    'bg-darken-3': { type: String, default: 'bg-darken-3', required: false },
    'bg-darken-4': { type: String, default: 'bg-darken-4', required: false },
    'bg-lighten-1': { type: String, default: 'bg-lighten-1', required: false },
    'bg-lighten-2': { type: String, default: 'bg-lighten-2', required: false },
    'bg-lighten-3': { type: String, default: 'bg-lighten-3', required: false },
    'bg-lighten-4': { type: String, default: 'bg-lighten-4', required: false },
    'border-black': { type: String, default: 'border-black', required: false }, // Border Colors
    'border-gray': { type: String, default: 'border-gray', required: false },
    'border-silver': { type: String, default: 'border-silver', required: false },
    'border-white': { type: String, default: 'border-white', required: false },
    'border-aqua': { type: String, default: 'border-aqua', required: false },
    'border-blue': { type: String, default: 'border-blue', required: false },
    'border-navy': { type: String, default: 'border-navy', required: false },
    'border-teal': { type: String, default: 'border-teal', required: false },
    'border-green': { type: String, default: 'border-green', required: false },
    'border-olive': { type: String, default: 'border-olive', required: false },
    'border-lime': { type: String, default: 'border-lime', required: false },
    'border-yellow': { type: String, default: 'border-yellow', required: false },
    'border-orange': { type: String, default: 'border-orange', required: false },
    'border-red': { type: String, default: 'border-red', required: false },
    'border-fuchsia': { type: String, default: 'border-fuchsia', required: false },
    'border-purple': { type: String, default: 'border-purple', required: false },
    'border-maroon': { type: String, default: 'border-maroon', required: false }
  }
}
