var domain = 'http://laravel-start-point.app'

export default {
  addContent: `${domain}/admin/pages/content/add`,
  allContent: `${domain}/admin/content/all`,
  allCountries: `${domain}/countries`,
  allLanguages: `${domain}/languages`,
  allPages: `${domain}/admin/pages/all?Pages`,
  allReferences: `${domain}/admin/references/all`,
  allResources: `${domain}/admin/resources/all`,
  associateReferences: `${domain}/admin/content/references`,
  associateCountries: `${domain}/admin/content/countries`,
  createContent: `${domain}/admin/content/create`,
  createPages: `${domain}/admin/pages/create`,
  createReference: `${domain}/admin/references`,
  deleteContent: `${domain}/admin/content/delete`,
  deletePages: `${domain}/admin/pages/delete`,
  deleteReference: `${domain}/admin/references`,
  layoutsList: `${domain}/admin/pages/layoutsList`,
  previewPage: `${domain}/admin/pages/preview`,
  removeContent: `${domain}/admin/pages/content/remove`,
  restorePages: `${domain}/admin/pages/restore`,
  toggleActive: `${domain}/admin/pages/toggleactive`,
  toggleContentActive: `${domain}/admin/content/toggleactive`,
  updateContent: `${domain}/admin/content/update`,
  updatePages: `${domain}/admin/pages/update`,
  updateReference: `${domain}/admin/references`,
  viewsList: `${domain}/admin/pages/viewslist`,
  updateTaxonomy: `${domain}/admin/taxonomies`,
  allTaxonomies: `${domain}/admin/taxonomy/all`
}
